# This name is shown in the status badge in the README
name: build

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

jobs:
  test:
    name: JDK ${{ matrix.java }} ${{ matrix.distribution }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 18]
        distribution: [temurin]
        include:
          - java: 17
            distribution: zulu
          - java: 17
            distribution: microsoft

    outputs:
        report-java: 17
        report-dist: temurin

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}

    - name: Run tests
      run: ./gradlew cleanTest test

    - name: Archive HTML test report
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-reports-java${{ matrix.java }}-${{ matrix.distribution }}-html
        path: "*/build/reports/**"

    - name: Archive JUnit test report
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-reports-java${{ matrix.java }}-${{ matrix.distribution }}-xml
        path: "*/build/test-results/**/*.xml"

    - name: Build JavaDoc
      run: ./gradlew assembleJavadoc

  publish-test-results:
    name: Publish test results
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'pull_request' }}

    permissions:
      checks: write
      pull-requests: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: test-reports-java${{ needs.test.outputs.report-java }}-${{ needs.test.outputs.report-dist }}-xml

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "**/*.xml"
