name: Reproducible binary

on:
  push:

jobs:
  verify:
    name: Verify signatures (JDK ${{ matrix.java }} ${{ matrix.distribution }})

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        distribution: [temurin]

    permissions:
      contents: write  # Allow uploading release artifacts

    steps:
    - name: check out code
      uses: actions/checkout@v3
      with:
        ref: 2.1.0-RC2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}

    - name: Build jars
      run: |
        java --version
        ./gradlew jar

    - name: Fetch keys
      run: gpg --no-default-keyring --keyring yubico --keyserver hkps://keys.openpgp.org --recv-keys 57A9DEED4C6D962A923BB691816F3ED99921835E

    - name: Download signatures from Maven Central
      timeout-minutes: 30
      run: |
        until wget https://repo1.maven.org/maven2/com/yubico/webauthn-server-attestation/2.1.0-RC2/webauthn-server-attestation-2.1.0-RC2.jar.asc; do sleep 180; done
        until wget https://repo1.maven.org/maven2/com/yubico/webauthn-server-core/2.1.0-RC2/webauthn-server-core-2.1.0-RC2.jar.asc; do sleep 180; done

    - name: Verify signatures from Maven Central
      run: |
        gpg --no-default-keyring --keyring yubico --verify webauthn-server-attestation-2.1.0-RC2.jar.asc webauthn-server-attestation/build/libs/webauthn-server-attestation-2.1.0-RC2.jar
        gpg --no-default-keyring --keyring yubico --verify webauthn-server-core-2.1.0-RC2.jar.asc webauthn-server-core/build/libs/webauthn-server-core-2.1.0-RC2.jar

    - name: Upload signatures to GitHub
      if: matrix.distribution == 'temurin'
      run: |
        RELEASE_DATA=$(curl -H "Authorization: Bearer ${{ github.token }}" ${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/2.1.0-RC2)
        UPLOAD_URL=$(jq -r .upload_url <<<"${RELEASE_DATA}" | sed 's/{?name,label}//')

        curl -X POST -H "Authorization: Bearer ${{ github.token }}" -H 'Content-Type: text/plain' --data-binary @webauthn-server-attestation-2.1.0-RC2.jar.asc "${UPLOAD_URL}?name=webauthn-server-attestation-2.1.0-RC2.jar.asc"
        curl -X POST -H "Authorization: Bearer ${{ github.token }}" -H 'Content-Type: text/plain' --data-binary @webauthn-server-core-2.1.0-RC2.jar.asc "${UPLOAD_URL}?name=webauthn-server-core-2.1.0-RC2.jar.asc"
