name: Reproducible binary

on:
  release:
    types: [published, created, edited, prereleased]

jobs:
  verify:
    name: Verify signatures (JDK ${{ matrix.java }} ${{ matrix.distribution }})

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
        distribution: [temurin, zulu, microsoft]

    steps:
    - name: check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}

    - name: Fetch keys
      run: gpg --no-default-keyring --keyring yubico --keyserver hkps://keys.openpgp.org --recv-keys 57A9DEED4C6D962A923BB691816F3ED99921835E

    - name: Build jars
      run: |
        java --version
        ./gradlew jar

    - name: Download signatures from Maven Central
      timeout-minutes: 30
      run: |
        until wget https://repo1.maven.org/maven2/com/yubico/webauthn-server-core/${{ github.ref_name }}/webauthn-server-attestation-${{ github.ref_name }}.jar.asc; do sleep 180; done
        until wget https://repo1.maven.org/maven2/com/yubico/webauthn-server-core/${{ github.ref_name }}/webauthn-server-core-${{ github.ref_name }}.jar.asc; do sleep 180; done

    - name: Verify signatures from Maven Central
      run: |
        gpg --no-default-keyring --keyring yubico --verify webauthn-server-attestation-${{ github.ref_name }}.jar.asc webauthn-server-attestation/build/libs/webauthn-server-attestation-${{ github.ref_name }}.jar
        gpg --no-default-keyring --keyring yubico --verify webauthn-server-core-${{ github.ref_name }}.jar.asc webauthn-server-core/build/libs/webauthn-server-core-${{ github.ref_name }}.jar

    - name: Upload signatures to GitHub and publish release
      run: |
        RELEASE_DATA=$(curl -H "Authorization: Bearer ${{ github.token }}" ${{ github.api_url }}/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }})
        RELEASE_URL=$(jq -r .url <<<"${RELEASE_DATA}")
        UPLOAD_URL=$(jq -r .upload_url <<<"${RELEASE_DATA}" | sed 's/{?name,label}//')

        curl -X POST -H "Authorization: Bearer ${{ github.token }}" --data-binary @webauthn-server-attestation-${{ github.ref_name }}.jar.asc "${UPLOAD_URL}"
        curl -X POST -H "Authorization: Bearer ${{ github.token }}" --data-binary @webauthn-server-core-${{ github.ref_name }}.jar.asc "${UPLOAD_URL}"

        curl -X POST -H "Authorization: Bearer ${{ github.token }}" -d '{"draft":false}' "${RELEASE_URL}"
